apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- name: vault
  version: 0.18.0
  repo: https://helm.releases.hashicorp.com
  valuesFile: values.yaml
  releaseName: vault
  namespace: vault
