apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: backend-infrastructure
build:
  artifacts:
    - image: recesser/apiserver
      docker:
        buildArgs:
          BINARY: apiserver
          RUST_VERSION: '{{ .RUST_VERSION }}'
    - image: recesser/rcssr
      docker:
        buildArgs:
          BINARY: rcssr
          RUST_VERSION: '{{ .RUST_VERSION }}'
    - image: recesser/schandler
      docker:
        buildArgs:
          BINARY: schandler
          RUST_VERSION: '{{ .RUST_VERSION }}'
  local:
    useDockerCLI: true
    useBuildkit: true
  tagPolicy:
    sha256: {}
deploy:
  statusCheck: false
  kustomize:
    buildArgs: [--enable-helm]
    paths:
      - manifests/argo_workflows
      - manifests/minio
      - manifests/mongo
      - manifests/recesser
      - manifests/vault
---
apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: template-executors
build:
  artifacts:
    - image: recesser/python-tensorflow-template
      context: template-executors/python-tensorflow
      docker: {}
  local:
    useDockerCLI: true
    useBuildkit: true
  tagPolicy:
    envTemplate:
      template: "{{.TEMPLATE_EXECUTORS_VERSION}}"
