apiVersion: v1
kind: ServiceAccount
metadata:
  name: schandler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: schandler
  name: schandler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schandler
  template:
    metadata:
      labels:
        app: schandler
    spec:
      containers:
      - name: schandler
        image: recesser/schandler
        imagePullPolicy: IfNotPresent
        command: ["schandler"]
        env:
        - name: RECESSER_APISERVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: apiserver-token
              key: token
        - name: RECESSER_POLLING_INTERVAL
          value: "1"
        - name: RECESSER_LOG_LEVEL
          value: debug
