[package]
name = "recesser-cli"
version = "0.1.0"
authors = ["nikstur <nikstur@outlook.com>"]
license = "MIT"
edition = "2021"

[[bin]]
name = "cite"
path = "src/main.rs"

[dependencies]
recesser-core = { version = "0.1", path = "../core" }
anyhow = "1.0"
clap = { version = "3.0", features = ["derive"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls-native-roots"] }
