[package]
name = "recesser-cli"
version = "0.1.0"
authors = ["nikstur <nikstur@outlook.com>"]
license = "MIT"
edition = "2021"

[[bin]]
name = "cite"
path = "src/main.rs"

[dependencies]
recesser-core = { version = "0.1.0", path = "../core" }
clap = { version = "3.0.7", features = ["derive"] }
anyhow = "1.0"
