apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-handler
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: handle-secrets
subjects:
  - kind: ServiceAccount
    name: apiserver
    namespace: recesser
roleRef:
  kind: Role
  name: secret-handler
  apiGroup: rbac.authorization.k8s.io
