[package]
name = "recesser-core"
version = "0.1.0"
authors = ["nikstur <nikstur@outlook.com>"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0"
blake3 = { version = "1.3", features = ["rayon"] }
base64 = "0.13"
serde = "1.0"
serde_json = "1.0"
