[package]
name = "recesser-server"
version = "0.1.0"
authors = ["nikstur <nikstur@outlook.com>"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0"
rust-s3 = { version = "0.28.0", features = ["blocking"] }
blake3 = "1.3.0"
base64 = "0.13.0"
