[alias]
l = "clippy --workspace --tests --bins"
f = "fmt --all -- --check"
c = "check --workspace"
t = "test"
b = "build"
a = "audit --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2020-0159"

[build]
target = "x86_64-unknown-linux-musl"
