# Pin exact version of tensorflow image
From tensorflow/tensorflow:2.9.1@sha256:a5c8c8995f16c63a9dbb59e586bed2e15dbf1024ac08065aaaad053c5173f83e

COPY entrypoint.sh .

ENTRYPOINT [ "bash", "entrypoint.sh" ]
