apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- name: minio
  version: 3.4.6
  repo: https://charts.min.io/
  valuesFile: values.yaml
  releaseName: minio
  namespace: minio
